-- Prevent deleted recurring task occurrences from being recreated by the scheduler.

alter table public.retail_task_series
  add column if not exists cancelled_at timestamptz;

comment on column public.retail_task_series.cancelled_at is
  'When set, the recurrence scheduler stops generating new occurrences for this series.';

create table if not exists public.retail_task_series_exclusions (
  id uuid primary key default gen_random_uuid(),
  series_id uuid not null references public.retail_task_series (id) on delete cascade,
  company_id uuid not null references public.companies (id) on delete cascade,
  shop_id uuid not null references public.shops (id) on delete cascade,
  due_date date not null,
  created_at timestamptz not null default now(),
  unique (series_id, due_date)
);

create index if not exists retail_task_series_exclusions_series_idx
  on public.retail_task_series_exclusions (series_id, due_date);

alter table public.retail_tasks
  add column if not exists materialized_by text not null default 'initial'
  check (materialized_by in ('initial', 'scheduler'));

comment on column public.retail_tasks.materialized_by is
  'initial = created with the series batch; scheduler = auto-generated by tickTaskRecurrence.';
